// Frontend/controle-estoque/src/pages/Home/index.tsx
import React from 'react';

import NavBar from '../../components/navBar';
import Cards from '../../components/cards';

import './styles.css';

const Home = () => {
    return (
        <>
        <NavBar />
            <div className="cardsArea">
                <Cards Header="Produtos" background="primary" linkName1="Novo produto" linkClass1="btn btn-outline-primary" linkName2="Listar produtos" linkAction1="/newProduct" linkAction2="/products" idx="Produto" />
                <Cards Header="Usuários" background="secondary" linkName1="Novo usuário" linkClass1="btn btn-outline-success" linkAction1="/newUser" linkName2="Listar usuários"  linkAction2="/users" idx="Usuario" />
                <Cards Header="Lançamentos" background="success" linkName1="Novo lançamento" linkClass1="btn btn-outline-info" linkName2="Listar lançamentos" linkAction1="/newMovement" linkAction2="/movements" idx="Lancamentos" />
            </div>
        </>
    );
}

export default Home;

// Frontend/controle-estoque-vue/src/pages/Home.vue
<template>
    <main class="container">
        <div class="row">
            <div class="col-md-4">
                <article id="card1" class="card border-primary">
                    <section class="card-header">Produtos</section>
                    <section class="body card-body text-primary">
                        <a href="/produtos" class="btn btn-outline-primary">Listar produtos</a>
                        <a href="/newProduct" class="btn btn-outline-primary">Novo produto</a>
                    </section>
                </article>
            </div>
            <div class="col-md-4">
                <article id="card2" class="card border-warning">
                    <section class="card-header">Usuários</section>
                    <section class="body card-body text-warning">
                        <a href="/produtos" class="btn btn-outline-warning">Listar usuários</a>
                        <a href="/" class="btn btn-outline-warning">Novo usuário</a>
                    </section>
                </article>
            </div>
            <div class="col-md-4">
                <article id="card3" class="card border-success">
                    <section class="card-header">Lançamentos</section>
                    <section class="body card-body text-success">
                        <a href="/produtos" class="btn btn-outline-success">Listar lançamentos</a>
                        <a href="/" class="btn btn-outline-success">Novo lançamento</a>
                    </section>
                </article>
            </div>
        </div>
    </main>
</template>

<script>
    export default {
        name: 'Home'
    }
</script>

<style scoped>
    .body {
        display: flex;
        justify-content: space-between;
    }
</style>
