// Frontend/controle-estoque-vue/src/pages/NewProduct.vue
<template>
    <main class="container">
        <h3>Novo produto</h3>
        <form class="form" @submit.prevent="salvar">
            <input id="sku" name="sku" placeholder="SKU" type="text" class="form-control" v-model="product.sku"/>
            <input id="name" name="name" placeholder="Nome" type="text" class="form-control" v-model="product.name"/>
            <input id="description" name="description" placeholder="Descrição" type="text" class="form-control" v-model="product.description"/>
            <input id="category" name="category" placeholder="Categoria" type="text" class="form-control" v-model="product.category"/>
            <input id="cust" name="name" placeholder="Preço de custo" type="number" class="form-control" v-model="product.cust"/>
            <section class="d-flex justify-content-evenly">
                <button type="submit" class="btn btn-success">Salvar</button>
                <button v-on:click="goBack" class="btn btn-danger">Cancelar</button>
            </section>
        </form>
    </main>
</template>

<script>
import Product from '../services/produtos';

export default {
    name: 'NewProduct',
    data() {
        return {
            product: {
                sku: '',
                name: '',
                description: '',
                category: '',
                cust: '',
                quantity: 0,
            },
        }
    },
    methods: {
        salvar(){
            Product.salvar(this.product).then((response) => {
                console.log(response.data);
                this.$router.push('produtos')
            }).catch((err) => {
                console.log(err);
            });
        },
        goBack(){
            this.$router.push('produtos')
        }
    }
}
</script>

<style scoped>
    .form{
        display: inline-block;
        justify-content: center;
        width: 25rem;
        margin-top: 2rem;
    }

    input {
        margin-bottom: 1rem;
    }
</style>

// Frontend/controle-estoque/src/pages/Products/newProduct/index.tsx
import React, { ChangeEvent, FormEvent, useState } from 'react';
import { Alert, Button, Container, Form, FormControl, Row } from 'react-bootstrap';
import { Link, useHistory } from 'react-router-dom';
import api from '../../../services/api';

import './styles.css';

interface Product {
    sku: string,
    name: string,
    description: string,
    category: string,
    cust: number,    
}

interface ErroMsg {
    msg: string,
}

const NewProduct = ({}) => {
    const history = useHistory();
    const token = sessionStorage.getItem('login');
    
    const [erroMsg, setErroMsg] = useState<ErroMsg>();

    const [formData, setFormData] = useState({
        sku: '',
        name: '',
        description: '',
        category: '',
        cust: 0,    
    });
    
    const [product, setProduct] = useState<Product[]>([]);

    function handleInputChange(event: ChangeEvent<HTMLInputElement>) {
        const {name, value} = event.target;
        setFormData({...formData, [name]: value});
    }
    
    async function handleSubmit(event: FormEvent) {
        event.preventDefault();

        const {sku, name, description, category, cust} = formData;

        const data = {
            sku: sku.toUpperCase(),
            name: name,
            description: description,
            category: category,
            cust: cust,    
        }
        api.post('product', data, {
            headers: {
                    "Authorization" : `bearer ${token}` 
            }
        }).then((response) => {
            setProduct(response.data);
            history.goBack();
        }).catch((error) => {
            if (error.response) {
                setErroMsg(error.response.data);
                console.log(error.response);
            }
        });               
    }

    async function handleClick() {
        history.goBack();
    }

    return (
        <main>
            <Container>
                <Row>
                    <Form onSubmit={handleSubmit}>
                        <h4 className="mb-5">Nova unidade de medida</h4>
                        <FormControl onChange={handleInputChange} className="mb-2" id="sku" name="sku" type="text" placeholder="SKU (entre 8 e 12 caracteres)" naria-label="sku" />
                        <FormControl onChange={handleInputChange} className="mb-2" id="name" name="name" type="text" placeholder="Nome" naria-label="name" />
                        <FormControl onChange={handleInputChange} className="mb-2" id="description" name="description" type="text" placeholder="Descrição" naria-label="description" />
                        <FormControl onChange={handleInputChange} className="mb-2" id="category" name="category" type="text" placeholder="Categoria" naria-label="category" />
                        <FormControl onChange={handleInputChange} className="mb-2" id="cust" name="cust" type="number" placeholder="Preço de custo" naria-label="cust" />
                        <div id="buttons">
                            <Button className="ml-4" variant="outline-success" type="submit">Salvar</Button>
                            <Link to="" onClick={handleClick} className="btn btn-outline-danger ml-4">Cancelar</Link>
                        </div>
                        <Alert className="text-danger">{erroMsg}</Alert>
                    </Form>
                </Row>  
            </Container>
        </main>      
    );
}

export default NewProduct;
