// Frontend/controle-estoque/src/components/navBar/index.tsx
import React from 'react';
import { Link, useHistory } from 'react-router-dom';
import { FiLock, FiLogIn } from 'react-icons/fi';
import { Navbar, Nav, Form, FormControl, Button, InputGroup} from 'react-bootstrap';

import './styles.css';

const NavBar = () => {
    return (
        <Navbar bg="light" fixed="top" expand="lg" className="mb-5">
        <Navbar.Toggle aria-controls="basic-navbar-nav" />
        <Navbar.Collapse id="basic-navbar-nav">
          <Nav className="mr-auto">
            <Nav.Link href="#home">Home</Nav.Link>
            <Nav.Link href="#link">Produtos</Nav.Link>
            <Nav.Link href="#link">Lançamentos</Nav.Link>
            <Nav.Link href="#link">Usuários</Nav.Link>
          </Nav>
        </Navbar.Collapse>
      </Navbar>
    );
  }

  export default NavBar;

// Frontend/controle-estoque-vue/src/components/Navbar.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
                <router-link></router-link>
              <a class="nav-link" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/produtos">Produtos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Lançamentos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Usuários</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
</template>

<script>
export default {
    name: 'Navbar'
}
</script>

<style scoped>

</style>
